name: tg_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytest
  - pytest-mock
  - pytest-cov
  - requests
  - biolink-model
  - jsonasobj2
  - linkml_runtime
  - humanize
  - sqlalchemy
  - pymysql
  - neo4j
  - psycopg2-binary
  - pandas
  - GEOparse
  - pyyaml
  - cwltool
  - snakemake
  - mgp
  - python-arango
  - gqlalchemy
  - streamlit
  - pyvis
  - networkx
  - graphql-server
  - strawberry-graphql
  - fastapi
  - uvicorn
  - gunicorn
  - ijson
  - gffutils
  - jinja2
  - python-multipart