services:
  fuseki:
    image: secoresearch/fuseki:latest
    container_name: ifx_fuseki
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: admin
      ENABLE_DATA_WRITE: "true"
      ENABLE_UPDATE: "true"
      QUERY_TIMEOUT: "10000,60000"
      TDB: "true"
    volumes:
      - fuseki_data:/fuseki
    restart: unless-stopped

volumes:
  fuseki_data:
