from src.interfaces.simple_enum import SimpleEnum

CHEMBL_PATENT_SOURCE_ID = 38
CHEMBL_FUNCTIONAL_ASSAY_CODE = 'F'
CHEMBL_BINDING_ASSAY_CODE = 'B'
CHEMBL_SMALL_MOLECULE_CODE = 'MOL'
CHEMBL_SINGLE_PROTEIN_CODE = 'SINGLE PROTEIN'
HUMAN_TAX_ID = 9606

class Prefix(SimpleEnum):
    CAS = 'CAS'                         	# from TNN
    CHEBI = 'CHEBI'                     	# from TNN
    CHEMBL_COMPOUND = 'CHEMBL.COMPOUND'  	# from TNN
    CL = 'CL'                           	# from TNN
    ComplexPortal = 'ComplexPortal'     	# from TNN
    dictyBase = 'dictyBase'             	# from TNN
    doi = 'doi'                         	# from TNN
    DOID = 'DOID'                       	# from TNN
    DRUGBANK = 'DRUGBANK'               	# from TNN
    DrugCentral = 'DrugCentral'         	# from TNN
    EC = 'EC'                           	# from TNN
    EFO = 'EFO'                         	# from TNN
    EMAPA = 'EMAPA'                     	# from TNN
    ENSEMBL = 'ENSEMBL'                 	# from TNN
    FB = 'FB'                           	# from TNN
    FBbt = 'FBbt'                       	# from TNN
    GO = 'GO'                           	# from TNN
    GTOPDB = 'GTOPDB'                   	# from TNN
    HGNC = 'HGNC'                       	# from TNN
    HGNC_FAMILY = 'HGNC.FAMILY'         	# from TNN
    HMDB = 'HMDB'                       	# from TNN
    HP = 'HP'                           	# from TNN
    ICD10 = 'ICD10'                     	# from TNN
    ICD9 = 'ICD9'                       	# from TNN
    INCHIKEY = 'INCHIKEY'               	# from TNN
    KEGG_COMPOUND = 'KEGG.COMPOUND'        	# from TNN
    KEGG_DISEASE = 'KEGG.DISEASE'          	# from TNN
    KEGG_REACTION = 'KEGG.REACTION'        	# from TNN
    MEDDRA = 'MEDDRA'                   	# from TNN
    medgen = 'medgen'                   	# from TNN
    MESH = 'MESH'                       	# from TNN
    MGI = 'MGI'                         	# from TNN
    MONDO = 'MONDO'                     	# from TNN
    MP = 'MP'                           	# from TNN
    NCBIGene = 'NCBIGene'               	# from TNN
    NCBITaxon = 'NCBITaxon'             	# from TNN
    NCIT = 'NCIT'                       	# from TNN
    OMIM = 'OMIM'                       	# from TNN
    OMIM_PS = 'OMIM.PS'                 	# from TNN
    orphanet = 'orphanet'               	# from TNN
    PANTHER_FAMILY = 'PANTHER.FAMILY'    	# from TNN
    PANTHER_PATHWAY = 'PANTHER.PATHWAY'  	# from TNN
    PMC = 'PMC'                         	# from TNN
    PMID = 'PMID'                       	# from TNN
    PR = 'PR'                           	# from TNN
    PUBCHEM_COMPOUND = 'PUBCHEM.COMPOUND' 	# from TNN
    REACT = 'REACT'                     	# from TNN
    RGD = 'RGD'                         	# from TNN
    RHEA = 'RHEA'                       	# from TNN
    RXCUI = 'RXCUI'                     	# from TNN
    SGD = 'SGD'                         	# from TNN
    SMPDB = 'SMPDB'                     	# from TNN
    SNOMEDCT = 'SNOMEDCT'               	# from TNN
    TCDB = 'TCDB'                       	# from TNN
    UBERON = 'UBERON'                   	# from TNN
    UMLS = 'UMLS'                       	# from TNN
    UNII = 'UNII'                       	# from TNN
    UniProtKB = 'UniProtKB'             	# from TNN
    WBbt = 'WBbt'                       	# from TNN
    WormBase = 'WormBase'               	# from TNN
    ZFA = 'ZFA'                         	# from TNN
    ZFIN = 'ZFIN'                       	# from TNN
    # ADDED Prefixes
    IFXProtein = "IFXProtein"
    IFXGene = "IFXGene"
    IFXTranscript = "IFXTranscript"
    BRENDA = "BRENDA"
    CCDS = "CCDS"
    CHEMBL_PROTEIN = "CHEMBL.PROTEIN"
    DIP = "DIP"
    DisProt = "DisProt"
    EN = "EN"
    IDEAL = "IDEAL"
    IMGT = "IMGT"            # previous prefix "IMGT/GENE-DB"
    miRBase = "miRBase"
    Name = "Name"
    OldSymbol = "OldSymbol"
    PIR = "PIR"
    ProteomicsDB = "ProteomicsDB"
    RefSeq = "RefSeq"
    Symbol = "Symbol"
    Synonym = "Synonym"
    SLP = "SLP"
    TranscriptSymbol = "Transcript"
    Vega = "Vega"
    Wikidata = "Wikidata"