from src.interfaces.simple_enum import SimpleEnum

CHEMBL_PATENT_SOURCE_ID = 38
CHEMBL_FUNCTIONAL_ASSAY_CODE = 'F'
CHEMBL_BINDING_ASSAY_CODE = 'B'
CHEMBL_SMALL_MOLECULE_CODE = 'MOL'
CHEMBL_SINGLE_PROTEIN_CODE = 'SINGLE PROTEIN'
HUMAN_TAX_ID = 9606

TARGET_GRAPH_VERSION = "1.0"

class DataSourceName(SimpleEnum):
    NCATSPounce = "NCATSPounce"
    TargetGraph = "Pharos 2.0 CSV"
    TargetGraphNCBI = "Pharos 2.0 CSV (NCBI)"
    ChEMBL = "ChEMBL"
    CCLE = "Cancer Cell Line Encyclopedia (CCLE)"
    Cellosaurus = "Cellosaurus"
    CLO = "Cell Line Ontology (CLO)"
    GO = "Gene Ontology (GO)"
    DrugCentral = "DrugCentral"
    JensenLab = "JensenLab"
    Antibodypedia = "Antibodypedia.com"
    NCBI = "NCBI"
    OldPharos = "Pharos 3.19"
    UniProt = "UniProt"
    Dummy = "Dummy DataSource"
    PostProcessing = "ETL Post Processing"
    RaMP = "RaMP"

class Prefix(SimpleEnum):
    CAS = 'CAS'                         	# from TNN
    CHEBI = 'CHEBI'                     	# from TNN
    CHEMBL_COMPOUND = 'CHEMBL.COMPOUND'  	# from TNN
    CL = 'CL'                           	# from TNN
    ComplexPortal = 'ComplexPortal'     	# from TNN
    dictyBase = 'dictyBase'             	# from TNN
    doi = 'doi'                         	# from TNN
    DOID = 'DOID'                       	# from TNN
    DRUGBANK = 'DRUGBANK'               	# from TNN
    DrugCentral = 'DrugCentral'         	# from TNN
    EC = 'EC'                           	# from TNN
    EFO = 'EFO'                         	# from TNN
    EMAPA = 'EMAPA'                     	# from TNN
    ENSEMBL = 'ENSEMBL'                 	# from TNN
    FB = 'FB'                           	# from TNN
    FBbt = 'FBbt'                       	# from TNN
    GO = 'GO'                           	# from TNN
    GTOPDB = 'GTOPDB'                   	# from TNN
    HGNC = 'HGNC'                       	# from TNN
    HGNC_FAMILY = 'HGNC.FAMILY'         	# from TNN
    HMDB = 'HMDB'                       	# from TNN
    HP = 'HP'                           	# from TNN
    ICD10 = 'ICD10'                     	# from TNN
    ICD9 = 'ICD9'                       	# from TNN
    INCHIKEY = 'INCHIKEY'               	# from TNN
    KEGG_COMPOUND = 'KEGG.COMPOUND'        	# from TNN
    KEGG_DISEASE = 'KEGG.DISEASE'          	# from TNN
    KEGG_REACTION = 'KEGG.REACTION'        	# from TNN
    MEDDRA = 'MEDDRA'                   	# from TNN
    medgen = 'medgen'                   	# from TNN
    MESH = 'MESH'                       	# from TNN
    MGI = 'MGI'                         	# from TNN
    MONDO = 'MONDO'                     	# from TNN
    MP = 'MP'                           	# from TNN
    NCBIGene = 'NCBIGene'               	# from TNN
    NCBITaxon = 'NCBITaxon'             	# from TNN
    NCIT = 'NCIT'                       	# from TNN
    OMIM = 'OMIM'                       	# from TNN
    OMIM_PS = 'OMIM.PS'                 	# from TNN
    orphanet = 'orphanet'               	# from TNN
    PANTHER_FAMILY = 'PANTHER.FAMILY'    	# from TNN
    PANTHER_PATHWAY = 'PANTHER.PATHWAY'  	# from TNN
    PMC = 'PMC'                         	# from TNN
    PMID = 'PMID'                       	# from TNN
    PR = 'PR'                           	# from TNN
    PUBCHEM_COMPOUND = 'PUBCHEM.COMPOUND' 	# from TNN
    REACT = 'REACT'                     	# from TNN
    RGD = 'RGD'                         	# from TNN
    RHEA = 'RHEA'                       	# from TNN
    RXCUI = 'RXCUI'                     	# from TNN
    SGD = 'SGD'                         	# from TNN
    SMPDB = 'SMPDB'                     	# from TNN
    SNOMEDCT = 'SNOMEDCT'               	# from TNN
    TCDB = 'TCDB'                       	# from TNN
    UBERON = 'UBERON'                   	# from TNN
    UMLS = 'UMLS'                       	# from TNN
    UNII = 'UNII'                       	# from TNN
    UniProtKB = 'UniProtKB'             	# from TNN
    WBbt = 'WBbt'                       	# from TNN
    WormBase = 'WormBase'               	# from TNN
    ZFA = 'ZFA'                         	# from TNN
    ZFIN = 'ZFIN'                       	# from TNN
    # ADDED Prefixes
    IFXProtein = "IFXProtein"
    IFXGene = "IFXGene"
    IFXTranscript = "IFXTranscript"
    BRENDA = "BRENDA"
    CCDS = "CCDS"
    CHEMBL_PROTEIN = "CHEMBL.PROTEIN"
    LIPIDMAPS = "LIPIDMAPS"
    DIP = "DIP"
    DisProt = "DisProt"
    EN = "EN"
    IDEAL = "IDEAL"
    IMGT = "IMGT"            # previous prefix "IMGT/GENE-DB"
    miRBase = "miRBase"
    Name = "Name"
    OldSymbol = "OldSymbol"
    PIR = "PIR"
    ProteomicsDB = "ProteomicsDB"
    RefSeq = "RefSeq"
    Symbol = "Symbol"
    Synonym = "Synonym"
    SLP = "SLP"
    TranscriptSymbol = "Transcript"
    Vega = "Vega"
    Wikidata = "Wikidata"

    # ramp prefixes
    RefMet = "RefMet"
    chemspider = "chemspider"
    pubchem = "pubchem"
    kegg = "kegg"
    rhea_comp = "rhea.comp"
    swisslipids = "swisslipids"
    kegg_glycan = "kegg_glycan"
    polymer = "polymer"
    lipidbank = "lipidbank"
    plantfa = "plantfa"


    # cell line data sources
    # 4DN = "4DN"
    Cellosaurus = "Cellosaurus"
    CCLE_ID = "CCLE_ID"
    Abcam = "Abcam"
    ABCD = "ABCD"
    Abeomics = "Abeomics"
    ABM = "ABM"
    AddexBio = "AddexBio"
    ArrayExpress = "ArrayExpress"
    ATCC = "ATCC"
    BCGO = "BCGO"
    BCRC = "BCRC"
    BCRJ = "BCRJ"
    BEI_Resources = "BEI_Resources"
    BioGRID_ORCS_Cell_line = "BioGRID_ORCS_Cell_line"
    BTO = "BTO"
    BioSample = "BioSample"
    BioSamples = "BioSamples"
    cancercelllines = "cancercelllines"
    CancerTools = "CancerTools"
    CBA = "CBA"
    CCLV = "CCLV"
    CCRID = "CCRID"
    CCTCC = "CCTCC"
    Cell_Biolabs = "Cell_Biolabs"
    Cell_Model_Passport = "Cell_Model_Passport"
    CGH_DB = "CGH-DB"
    ChEMBL_Cells = "ChEMBL-Cells"
    ChEMBL_Targets = "ChEMBL-Targets"
    CLDB = "CLDB"
    CLO = "CLO"
    CLS = "CLS"
    ColonAtlas = "ColonAtlas"
    Coriell = "Coriell"
    Cosmic = "Cosmic"
    Cosmic_CLP = "Cosmic-CLP"
    dbGAP = "dbGAP"
    dbMHC = "dbMHC"
    DepMap = "DepMap"
    DGRC = "DGRC"
    DiscoverX = "DiscoverX"
    DSHB = "DSHB"
    DSMZ = "DSMZ"
    DSMZCellDive = "DSMZCellDive"
    EBiSC = "EBiSC"
    ECACC = "ECACC"
    EGA = "EGA"
    ENCODE = "ENCODE"
    ESTDAB = "ESTDAB"
    FCDI = "FCDI"
    FCS_free = "FCS-free"
    FlyBase_Cell_line = "FlyBase_Cell_line"
    GDSC = "GDSC"
    GeneCopoeia = "GeneCopoeia"
    Genomeditech = "Genomeditech"
    GEO = "GEO"
    HipSci = "HipSci"
    Horizon_Discovery = "Horizon_Discovery"
    hPSCreg = "hPSCreg"
    Hysigen = "Hysigen"
    IARC_TP53 = "IARC_TP53"
    IBRC = "IBRC"
    ICLC = "ICLC"
    ICLDB = "ICLDB"
    IGRhCellID = "IGRhCellID"
    IGSR = "IGSR"
    IHW = "IHW"
    Imanis = "Imanis"
    Innoprot = "Innoprot"
    IPD_IMGT_HLA = "IPD-IMGT/HLA"
    IZSLER = "IZSLER"
    JCRB = "JCRB"
    KCB = "KCB"
    KCLB = "KCLB"
    Kerafast = "Kerafast"
    KYinno = "KYinno"
    LiGeA = "LiGeA"
    LIMORE = "LIMORE"
    LINCS_HMS = "LINCS_HMS"
    LINCS_LDP = "LINCS_LDP"
    Lonza = "Lonza"
    MCCL = "MCCL"
    MeSH = "MeSH"
    MetaboLights = "MetaboLights"
    Millipore = "Millipore"
    MMRRC = "MMRRC"
    NCBI_Iran = "NCBI_Iran"
    NCI_DTP = "NCI-DTP"
    NHCDR = "NHCDR"
    NIHhESC = "NIHhESC"
    NISES = "NISES"
    NRFC = "NRFC"
    PerkinElmer = "PerkinElmer"
    PharmacoDB = "PharmacoDB"
    PRIDE = "PRIDE"
    Progenetix = "Progenetix"
    PubChem_Cell_line = "PubChem_Cell_line"
    RCB = "RCB"
    RIKEN_BRC_EPD = "RIKEN_BRC_EPD"
    Rockland = "Rockland"
    RSCB = "RSCB"
    Sigma_Aldrich = "Sigma-Aldrich"
    SKIP = "SKIP"
    SKY_M_FISH_CGH = "SKY/M-FISH/CGH"
    SLKBase = "SLKBase"
    TKG = "TKG"
    TNGB = "TNGB"
    TOKU_E = "TOKU-E"
    Ubigene = "Ubigene"
    WiCell = "WiCell"
    Ximbio = "Ximbio"
